### ISSUE TITLE
uri was not specified

### ISSUE THREAD

**Issue by jeusdi** [vjuranek/docker-build-step-plugin#40]
My docker service configuration is like:

> [Unit]
> Description=Docker Application Container Engine
> Documentation=https://docs.docker.com
> After=network.target docker.socket
> Requires=docker.socket
> 
> [Service]
> Type=notify
> ExecStart=/usr/bin/docker daemon -H fd:// -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock
> MountFlags=slave
> LimitNOFILE=1048576
> LimitNPROC=1048576
> LimitCORE=infinity
> TimeoutStartSec=0
> Delegate=yes
> 
> [Install]
> WantedBy=multi-user.target

My job dumps me that:
> 
> java.lang.NullPointerException: uri was not specified
> 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:204)
> 	at com.github.dockerjava.core.DockerClientConfig$DockerClientConfigBuilder.withUri(DockerClientConfig.java:406)
> 	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder$DescriptorImpl.createDockerClient(DockerBuilder.java:120)
> 	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder$DescriptorImpl.getDockerClient(DockerBuilder.java:204)
> 	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder.perform(DockerBuilder.java:68)
> 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
> 	at hudson.model.Build$BuildExecution.build(Build.java:205)
> 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
> 	at hudson.model.Run.execute(Run.java:1720)
> 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 	at hudson.model.ResourceController.execute(ResourceController.java:98)
> 	at hudson.model.Executor.run(Executor.java:410)
> Build step 'Execute Docker command' marked build as failure
> Finished: FAILURE

**Comment by daper** [comment]
Hi! You don't need to expose tcp api of docker, just use the unix socket. Check out if you have defined the Docker URL in "Configure System" > "Docker Builder". I have this one "unix:///var/run/docker.sock". Before click "Test Connection" make sure you, have clicked  "Apply" to save settings.

**Comment by harirenumanu** [comment]
Something went wrong, cannot connect to https://hub.docker.com/, cause: null
