### ISSUE TITLE
Unsupported protocol scheme found: 'http://mint-gitlab:2375'. Only 'tcp://' or 'unix://' supported.

### ISSUE THREAD

**Issue by norricorp** [vjuranek/docker-build-step-plugin#54]
plugin 1.38
com.github.dockerjava.api.exception.DockerClientException: Unsupported protocol scheme found: 'http://mint-gitlab:2375'. Only 'tcp://' or 'unix://' supported.
	at com.github.dockerjava.core.DefaultDockerClientConfig.checkDockerHostScheme(DefaultDockerClientConfig.java:96)
	at com.github.dockerjava.core.DefaultDockerClientConfig.<init>(DefaultDockerClientConfig.java:82)
	at com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:431)
	at com.github.dockerjava.core.DockerClientBuilder.getInstance(DockerClientBuilder.java:23)
	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder$DescriptorImpl.createDockerClient(DockerBuilder.java:139)
	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder$DescriptorImpl.getDockerClient(DockerBuilder.java:216)

**Comment by norricorp** [comment]
Just tried with v1.39. Same problem.

**Comment by Bigd271** [comment]
I just replaced "https" with "tcp" and it worked.

**Comment by norricorp** [comment]
Interesting but mine already says "tcp" in the docker options. 
I have actually got round the problem by not using the plugin and just using docker commands in shell commands.

**Comment by dbaikov** [comment]
Having the same issue :( Any update on this one? Thanks.

**Comment by livvius** [comment]
Same also

**Comment by dduuch** [comment]
I have the same issue, but I find a way to solve it.
Go to Jenkins dir and grep http://localhost:4243/ . One my case, one file have this parameter: org.jenkinsci.plugins.dockerbuildstep.DockerBuilder.xml .
I change directly in this file from http://localhost:4243/ to tcp://localhost:4243. Restart Jenkins service and  the problem disappeared

**Comment by vijayst** [comment]
@norricorp Will be interested to know how to use shell commands. Not able to get docker-build-step-plugin to behave sensibly. They make an assumption we don't know docker!

**Comment by norricorp** [comment]
So I did this as an execute shell post build step
cd $WORKSPACE
docker build -t groovytest-$BUILD_NUMBER:jenkins .
docker create --name groovytest-$BUILD_NUMBER groovytest-$BUILD_NUMBER:jenkins
docker start groovytest-$BUILD_NUMBER
docker tag groovytest-$BUILD_NUMBER:jenkins centos7:5000/groovytest-jenkins:$BUILD_NUMBER
docker push centos7:5000/groovytest-jenkins:$BUILD_NUMBER
