### ISSUE TITLE
NullpointerException if a container is not exposing ports

### ISSUE THREAD

**Issue by flybyray** [vjuranek/docker-build-step-plugin#57]

**Comment by swardi** [comment]
For me this only becomes issue in SCM polling. Otherwise manual build is completing fine. 

Exception trace is:

```
ERROR: Failed to record SCM polling
java.lang.NullPointerException
	at org.jenkinsci.plugins.dockerbuildstep.DockerEnvContributor.exportPortBindings(DockerEnvContributor.java:71)
	at org.jenkinsci.plugins.dockerbuildstep.DockerEnvContributor.buildEnvironmentFor(DockerEnvContributor.java:56)
	at hudson.model.Run.getEnvironment(Run.java:2269)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:922)
	at hudson.plugins.git.GitSCM.getParamExpandedRepos(GitSCM.java:416)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:622)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:587)
	at hudson.scm.SCM.compareRemoteRevisionWith(SCM.java:391)
	at hudson.scm.SCM.poll(SCM.java:408)
	at hudson.model.AbstractProject._poll(AbstractProject.java:1460)
	at hudson.model.AbstractProject.poll(AbstractProject.java:1363)
	at com.cloudbees.jenkins.GitHubPushTrigger$1.runPolling(GitHubPushTrigger.java:108)
	at com.cloudbees.jenkins.GitHubPushTrigger$1.run(GitHubPushTrigger.java:134)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by vjuranek** [comment]
Done in 7b52e560e27c20f6d0b9d8aeac6c25be6f20d64b
