### ISSUE TITLE
Image Builds Fail With "Read Timed Out" When COPYing Files

### ISSUE THREAD

**Issue by heathharrelson** [vjuranek/docker-build-step-plugin#61]
We recently had an issue where image builds were failing with the error "Read timed out" when Dockerfile COPY lines took more than a few seconds to copy a file. For example, the following comes from the log of a job that copies a ~14MB JAR file:

```
[Docker] INFO: Creating docker image from /var/lib/jenkins/jobs/LGH-Next_Scoring_image/workspace/Dockerfile
[Docker] INFO: BuildResponseItem[stream=Step 1 : FROM octri.ohsu.edu/java
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream= ---> 40239aac50b9
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream=Step 2 : CMD /usr/bin/java -jar /scoring.jar
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream= ---> Using cache
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream= ---> 59c2308bb675
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream=Step 3 : EXPOSE 8080
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream= ---> Using cache
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream= ---> 2f0b51703b95
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream=Step 4 : COPY target/scoring-*.jar /
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] ERROR: Failed to creating docker image:Read timed out
ERROR: Processing failed due to a bug in the code. Please report this to jenkinsci-users@googlegroups.com
java.lang.RuntimeException: java.lang.RuntimeException: java.net.SocketTimeoutException: Read timed out
	at org.jenkinsci.plugins.dockerbuildstep.cmd.CreateImageCommand.execute(CreateImageCommand.java:112)
	at org.jenkinsci.plugins.dockerbuildstep.DockerBuilder.perform(DockerBuilder.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.build(MavenModuleSetBuild.java:915)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:866)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```
Full stack trace: [scoring-failure-trace.txt](https://github.com/vjuranek/docker-build-step-plugin/files/922839/scoring-failure-trace.txt)

After a bit of bit of experimentation, I was able to work around the timeout by applying the following patch to the Docker build step plugin:

```diff
diff --git a/src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java b/src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java
index c11fa79..5c0ef15 100644
--- a/src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java
+++ b/src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java
@@ -134,6 +134,7 @@ public class DockerBuilder extends Builder {
             // using jaxrs/jersey implementation here (netty impl is also available)
             DockerCmdExecFactory dockerCmdExecFactory = new DockerCmdExecFactoryImpl()
                     .withConnectTimeout(1000)
+                    .withReadTimeout(60000)
                     .withMaxTotalConnections(1)
                     .withMaxPerRouteConnections(1);
             return DockerClientBuilder.getInstance(configBuilder).withDockerCmdExecFactory(dockerCmdExecFactory).build();
```

I don't know if this addresses the root cause of the problem or if it's even reasonable, but it worked in my case.

Docker Versions:

```
octrici:~ $ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

Jenkins Versions:

* Jenkins: 1.580.3
* Credentials Plugin: 1.22
* Docker Commons Plugin: 1.6
* docker-build-step Plugin: 1.41

**Comment by ohbus** [comment]
I am also facing similar issue
